services:
  db:
    image: postgres:17-alpine
    container_name: postgres_local_alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: fred
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=pt-BR"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: