services:
  db:
    image: postgres:17-alpine
    container_name: postgres_local_alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=pt-BR"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create-db-env.sql:/docker-entrypoint-initdb.d/create_database.sql
volumes:
  pgdata:
    driver: "local"
    