CREATE ROLE pulso_admin WITH LOGIN NOSUPERUSER NOCREATEDB CREATEROLE   INHERIT NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 PASSWORD 'PULSO_ADMIN';
CREATE ROLE pulso_web   WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 PASSWORD 'PULSO_WEB';

CREATE DATABASE pulso_db WITH OWNER = PULSO_ADMIN TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'pt_BR.utf8' LC_CTYPE = 'pt_BR.utf8' LOCALE_PROVIDER = 'libc' CONNECTION LIMIT = -1 IS_TEMPLATE = False;
ALTER DATABASE  pulso_db OWNER TO pulso_admin;

\connect pulso_db
CREATE SCHEMA  pulso AUTHORIZATION pulso_admin;
